### Site Settings ###
title               : Vyshnav Gangadharan
description         : >-                               # >- means to ignore newlines until "url:"
                      An engineer who loves
                      Graphics Designing, Film making, Video editing & Coding.

url                 : "https://vyshnav.xyz/"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : Vyshnav2255/MyWebsite

### Author Info ###
author:
  name              : Vyshnav Gangadharan
  image             : /Images/me.png
  dribbble          : vyshnav_
  behance           : vyshnav_g
# email             : vyshnav003@gmail.com
  github            : Vyshnav2255
  instagram         : vyshnavgangadharan
  linkedin          : vyshnav-gangadharan
  twitter           : ThisIsVyshnav
#  goodreads         : vyshnav


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  blogs:
    output: true 
    permalink: /blog/:name

  books:
    output: true 
    permalink: /book-notes/:title
  
  microblogs:
    output: true 
    permalink: /microblog/:title

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"     
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "microblog"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-admin

url: "https://vyshnav.xyz" # the base hostname & protocol for your site
  
### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock