### Site Settings ###
title               : Vyshnav Gangadharan
description         : >-                               # >- means to ignore newlines until "url:"
                      An engineer who loves
                      Graphics Designing, Film making, Video editing & Coding.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : Vyshnav2255/MyWebsite

### Author Info ###
author:
  name              : Vyshnav Gangadharan
  image             : /Images/me.png
  dribbble          : vyshnav_
  behance           : vyshnav_g
  spotify           : 1h2t9epiiju145cozov3wb3hm?si=Rtdk-r_ZQH-2_vLEjN2jiw
# email             : vyshnav003@gmail.com
# facebook          : your_username
  github            : Vyshnav2255
# gitlab            : your_username
  instagram         : vyshnavgangadharan
  linkedin          : vyshnav-gangadharan
  medium            : vyshnav003_17133
  reddit            : VyshnavVaichu
  telegram          : Vyshnav_g
# soundcloud        : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : _vyshnav_
# vimeo             : your_username
  youtube           : startcameraaction


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  freebies:
    output: true 
    permalink: /blog/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"     
  - scope:
      path: ""
      type: "freebies"
    values:
      layout: "posts"

plugins:
  - jemoji
  - jekyll-seo-tag

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock