### Site Settings ###
title               : Vyshnav Gangadharan
description         : >-                               # >- means to ignore newlines until "url:"
                      An engineer who loves
                      Graphics Designing, Film making, Video editing & Coding.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Vyshnav Gangadharan
  image             : /Images/me.png
  behance           : vyshnav0033b60
  dribbble          : vyshnav_
# email             : vyshnav003@gmail.com
# facebook          : your_username
  github            : Vyshnav2255
# gitlab            : your_username
  instagram         : vyshnavgangadharan
  linkedin          : vyshnav-gangadharan
  medium            : vyshnav003_17133
  reddit            : VyshnavVaichu
  telegram          : Vyshnav_g
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : _vyshnav_
# vimeo             : your_username
  youtube           : startcameraaction


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  freebies:
    output: true 
    permalink: /blog/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"     
  - scope:
      path: ""
      type: "freebies"
    values:
      layout: "page"

plugins:
  - jemoji

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock