### Site Settings ###
title               : Vyshnav Gangadharan
description         : >-                               # >- means to ignore newlines until "url:"
                      A UI/UX designer who loves Coding, Illustrating & creating 3D stuff

url                 : "https://vyshnav.xyz"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : Vyshnav2255/MyWebsite
version             : "IX"               # version of your site

### Author Info ###
author:
  name              : Vyshnav Gangadharan
  image             : /Images/me.jpeg
  Twitter           : vyshnav_xyz
  Layers            : vyshnav
#  behance           : vyshnav_g
  Github            : Vyshnav2255
  Figma             : vyshnav
  Linkedin          : vyshnav-gangadharan
#  goodreads         : vyshnav
  Bio.link          : 
  Peerlist          : vyshnav_xyz


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  blogs:
    output: true 
    permalink: /blog/:name

  books:
    output: true 
    permalink: /book-notes/:title
  
  microblogs:
    output: true 
    permalink: /microblog/:title

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"     
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "microblog"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-admin

sass:
    style: compressed
  
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor